grappelli/urls.py
# coding: utf-8

from django.urls import re_path

from .views.related import AutocompleteLookup, M2MLookup, RelatedLookup
from .views.switch import switch_user
from .settings import SWITCH_USER_REGEX


urlpatterns = [

    # FOREIGNKEY & GENERIC LOOKUP
    re_path(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    re_path(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    re_path(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    re_path(r'^switch/user/(?P<object_id>{})/$'.format(SWITCH_USER_REGEX), switch_user, name="grp_switch_user"),
]

testproject/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    ('^$', 'django.views.generic.simple.redirect_to', {'url': '/admin/'}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^grappelli/', include('grappelli.urls')),
#   (r'^grappelli/test/', include('grappellitest.urls')),
    (r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        (r'^-media/(.*)$', 'django.views.static.serve', {
            'document_root': settings.GRAPPELLI_MEDIA_ROOT, 'show_indexes': True}),
    )

theme/urls.py
# coding: utf-8

from django.conf.urls.defaults import *

urlpatterns = patterns('',
    
    # BOOKMARKS
    url(r'^bookmark/add/$', 'grappelli.theme.views.bookmarks.add_bookmark', name="grp_bookmark_add"),
    url(r'^bookmark/remove/$', 'grappelli.theme.views.bookmarks.remove_bookmark', name="grp_bookmark_remove"),
    url(r'^bookmark/get/$', 'grappelli.theme.views.bookmarks.get_bookmark', name="grp_bookmark_get"),
    
    # HELP
    url(r'^help/(?P<object_id>\d+)/$', 'grappelli.theme.views.help.detail', name="grp_help_detail"),
    url(r'^help', 'grappelli.theme.views.help.help', name="grp_help"),
    
    # GENERIC
    url(r'^obj_lookup/$', 'grappelli.theme.views.generic.generic_lookup', name="grp_generic_lookup"),
    
    # FOREIGNKEY LOOKUP
    url(r'^related_lookup/$', 'grappelli.theme.views.related.related_lookup', name="grp_related_lookup"),
    url(r'^m2m_lookup/$', 'grappelli.theme.views.related.m2m_lookup', name="grp_m2m_lookup")
    
    # AUTOCOMPLETE LOOKUP
    #url(r'^autocomplete_lookup/$', 'grappelli.theme.views.related.autocomplete_lookup', name="grp_autocomplete_lookup"),
    #url(r'^autocomplete_lookup_id/$', 'grappelli.theme.views.related.autocomplete_lookup_id', name="grp_autocomplete_lookup_id"),
    
    # M2M AUTOCOMPLETE LOOKUP
    #url(r'^m2m_autocomplete_lookup/$', 'grappelli.theme.views.related.m2m_autocomplete_lookup', name="grp_m2m_autocomplete_lookup"),
    #url(r'^m2m_autocomplete_lookup_id/$', 'grappelli.theme.views.related.m2m_autocomplete_lookup_id', name="grp_m2m_autocomplete_lookup_id"),
    
)

testproject/testapp/models.py
from django.db import models

from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.contrib.sites.models import Site


class DjangoTextFields(models.Model):
    char_test      = models.CharField(u"CharField", max_length=255, help_text=u"A string field, for small- to large-sized strings (required).")
    slug_test      = models.SlugField(u"SlugField", max_length=50, blank=True, help_text=u"A slug is a short label for something, containing only letters, numbers, underscores or hyphens. They're generally used in URLs.")
    text_test      = models.TextField(u"TextField", blank=True, help_text=u"A large text field. The admin represents this as a textarea (a multi-line input).")
    #auto_test      = models.AutoField(u"AutoField", max_length=255, blank=True)
    # CommaSeparatedIntegerField
    # XMLField

    def __unicode__(self):
        return u'%s' % self.char_test

    class Meta:
        verbose_name = u'Django text fields test'
        verbose_name_plural = u'Django text fields test'


class DjangoTimeFields(models.Model):
    datetime_test  = models.DateTimeField(u"DateTimeField")
    date_test      = models.DateField(u"DateField", blank=True)
    time_test      = models.TimeField(u"TimeField", blank=True)

    def __unicode__(self):
        return u'%s' % self.datetime_test

    class Meta:
        verbose_name = u'Django time fields test'
        verbose_name_plural = u'Django time fields test'


class DjangoNumberFields(models.Model):
    char_test      = models.CharField(u"Test name", max_length=255)
    decimal_test   = models.DecimalField(u"DecimalField", blank=True, max_digits=5, decimal_places=4, help_text=u"A fixed-precision decimal number, represented in Python by a Decimal instance.")
    integer_test   = models.IntegerField(u"IntegerField", blank=True, help_text=u"An integer. The admin represents this as a text input (single-line).")
    float_test     = models.FloatField(u"FloatField", blank=True, help_text=u"A floating-point number.")
    pinteger_test  = models.PositiveIntegerField(u"PositiveIntegerField", blank=True, help_text=u"Like an IntegerField, but must be positive.")
    psinteger_test = models.PositiveSmallIntegerField(u"PositiveSmallIntegerField", blank=True, help_text=u"Like a PositiveIntegerField, but only allows values under a certain (database-dependent) point.")
    sinteger_test  = models.SmallIntegerField(u"SmallIntegerField", blank=True, help_text=u"Like an IntegerField, but only allows values under a certain (database-dependent) point.")
    boolean_test   = models.BooleanField(u"BooleanField", blank=True, default=True, help_text=u"A true/false field.")
    nboolean_test  = models.NullBooleanField(u"NullBoolean", blank=True, help_text=u"Like a BooleanField, but allows NULL  as one of the options. Use this instead of a BooleanField  with null=True.")

    def __unicode__(self):
        return u'%s' % self.char_test

    class Meta:
        verbose_name = u'Django number fields test'
        verbose_name_plural = u'Django number fields test'


class DjangoNetFields(models.Model):
    email_test     = models.EmailField(u"EmailField", max_length=255, help_text=u"A CharField that checks that the value is a valid e-mail address.")
    ip_test        = models.IPAddressField(u"IPAddressField", blank=True, help_text=u"An IP address, in string format (e.g. 192.0.2.30)")
    url_test       = models.URLField(u"URLField", max_length=255, blank=True, verify_exists=False, help_text=u"A CharField  for a URL.")

    def __unicode__(self):
        return u'%s' % self.email_test

    class Meta:
        verbose_name = u'Django net fields test'
        verbose_name_plural = u'Django net fields test'


class DjangoFileFields(models.Model):
    char_test      = models.CharField(u"Test name", max_length=255)
    file_test      = models.FileField(u"FileField", blank=True, upload_to='uploads/', help_text=u"A CharField  for a URL.")
    image_test     = models.ImageField(u"ImageField", blank=True, upload_to='uploads/', help_text=u"Like FileField, but validates that the uploaded object is a valid image.")

    def __unicode__(self):
        return u'%s' % self.char_test

    class Meta:
        verbose_name = u'Django file fields test'
        verbose_name_plural = u'Django file fields test'


class DjangoRelatedFields(models.Model):
    char_test      = models.CharField(u"Test name", max_length=255)
    fk_test        = models.ForeignKey(Site, verbose_name=u"ForeignKey", help_text=u"A many-to-one relationship.")
#   inline_test    = models.ForeignKey('InlineTabularTest', verbose_name=u"ForeignKey (inline tabular)", blank=True)
#   inline_test2   = models.ForeignKey('InlineStackedTest', verbose_name=u"ForeignKey (inline stacked)", blank=True)
    m2m_test       = models.ManyToManyField(Site, verbose_name=u"ManyToManyField", blank=True, related_name='many_to_many', help_text=u"A many-to-many relationship.")
    ooo_test       = models.OneToOneField(Site, verbose_name=u"OneToOneField", blank=True, related_name='one_to_one', help_text=u"A one-to-one relationship. Conceptually, this is similar to a ForeignKey  with unique=True, but the 'reverse' side of the relation will directly return a single object.")

    def __unicode__(self):
        return u'%s' % self.test_name

    class Meta:
        verbose_name = u'Django related fields test'
        verbose_name_plural = u'Django related fields test'


#class InlineStackedTest(models.Model):
#    char_test = models.CharField(u"Char Field", max_length=255, blank=True)
#    date_added  = models.DateField(u"DateField", auto_now_add=True, auto_now=True, blank=True, null=True)
#
#    def __unicode__(self):
#        return u'%s' % self.char_test
#

#class InlineTabularTest(models.Model):
#    char_test = models.CharField(u"Char Field", max_length=255, blank=True)
#    date_added  = models.DateField(u"DateField", auto_now_add=True, auto_now=True, blank=True, null=True)
#
#    def __unicode__(self):
#        return u'%s' % self.char_test
#

class GrappelliRelatedFields(models.Model):
    char_test      = models.CharField(u"Test name", max_length=255)
    fk_test     = models.ForeignKey(Site, verbose_name=u"FK Autocomplete")
    gr_test     = models.ForeignKey(User, verbose_name=u"ForeignKey", null=True, blank=True)
    gr_m2m      = models.ManyToManyField(User, verbose_name=u"ManyToManyField", null=True, blank=True, related_name="m2m_user")
    m2m_test    = models.ManyToManyField(Site, verbose_name=u"M2M Autocomplete", blank=True, null=True, related_name="m2m_site")
    content_type = models.ForeignKey(ContentType, blank=True, null=True, related_name="content_type")
    object_id = models.PositiveIntegerField(blank=True, null=True)
    content_object = generic.GenericForeignKey("content_type", "object_id")

    def __unicode__(self):
        return u'%s' % self.test_name

    class Meta:
        verbose_name = u'Django related fields test'
        verbose_name_plural = u'Django related fields test'


class GrappelliEnhancedFields(models.Model):
    char_test   = models.CharField(u"CharField", max_length=255, blank=True)
    slug_test   = models.SlugField(u"SlugField", max_length=50, help_text="Drag the gear (which should be a crosshair..) to set the slug from another field")
    slug_test2  = models.SlugField(u"SlugField", max_length=50, help_text="Standalone", null=True, blank=True)
    mce_test    = models.TextField(u"TinyMCE", blank=True)

    def __unicode__(self):
        return u'%s' % self.char_test

    class Meta:
        verbose_name = u'Grappelli enhanced fields test'
        verbose_name_plural = u'Grappelli enhanced fields test'


#class GrappelliInlines(models.Model):
#    inline_test  = models.ForeignKey('InlineTabularTest', verbose_name=u"ForeignKey (inline tabular)", blank=True, null=True)
#    inline_test2 = models.ForeignKey('InlineStackedTest', verbose_name=u"ForeignKey (inline stacked)", blank=True, null=True)
#
#    def __unicode__(self):
#        return u'%s - %s' % (self.test_name, self.fk_test)
#
#    class Meta:
#        verbose_name = u'Grappelli Field test'
#        verbose_name_plural = u'Grappelli Field tests'

templates/grappellitest/css-styles.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="{{ root_path }}">Home</a> &rsaquo; Tests</div>{% endblock %}
{% block title %}Tests{% endblock %}

{% block content %}

<h1>Grappelli tests</h1>

<div id="content-main">
  <h3><a href="{% url test-css-styles %}">CSS Styles</a></h3>
  <p>A showcase of importants CSS style rules.</p>

  <h3><a href="{% url test-js-grappelli %}">Grappelli JavaScript tests</a></h3>
  <p>Unit tests for grappelli core widgets.</p>

  <h3><a href="{% url test-js-contrib %}">Contrib JavaScript tests</a></h3>
  <p>Unit tests for externals libraries.</p>

  <h3><a href="{% url test-functional %}">Functional tests</a></h3>
  <p>Functional tests of each widgets.</p>
</div>
{% endblock %}

templates/grappellitest/index.html
{% extends "admin/base.html" %}
{% load i18n %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="{{ root_path }}">Home</a> &rsaquo; Tests</div>{% endblock %}
{% block title %}Tests{% endblock %}
{% block bodyclass %}dashboard documentation {% endblock %}

{% block content %}

<h1>Grappelli tests</h1>
<div class="container-grid rte">
    <div class="module">
        <h2><a href="{% url test-css-styles %}">CSS Styles</a></h2>
        <p>A showcase of importants CSS style rules.</p>
    </div>
    <div class="module">
        <h2>JavaScript unit tests</h2>
        <ul>
            <li><a href="{% url test-js-grappelli %}">Unit tests for grappelli core widgets.</a></li>
            <li><a href="{% url test-js-contrib %}">Unit tests for externals libraries.</li>
        </ul>
    </div>
    <div class="module">
        <h2><a href="{% url test-functional %}">Functional tests</a></h2>
        <p>Functional tests of each widgets.</p>
    </div>
</div>

{% endblock %}

templates/grappellitest/test-base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr" >
    <head>
        <title>QUnit Test Suite|{% block js %}{% endblock %}</title>
        <script type="text/javascript" src="/grappelli/jsi18n/grappelli/"></script> 
        
        {% block js.jquery %}{% endblock %}
        {% block js.contrib %}{% endblock %}
        {% block js.grappelli %}{% endblock %}

        <script type="text/javascript"> 
            // Use this to remove *all* effects (not recommended)
            // $.fx.off = true;
            // $.fx.speeds._default = 0; // force fx.off for jQuery < 1.8 (http://dev.jqueryui.com/ticket/4328)
     
            $.grappelli.conf.extend({
                lang:               'fr',
                rtl:                false,
                content_types:      {1: {pk: 1, app: 'auth', model: 'permission'},2: {pk: 2, app: 'auth', model: 'group'},3: {pk: 3, app: 'auth', model: 'user'},4: {pk: 4, app: 'auth', model: 'message'},5: {pk: 5, app: 'admin', model: 'logentry'},6: {pk: 6, app: 'contenttypes', model: 'contenttype'},7: {pk: 7, app: 'sessions', model: 'session'},8: {pk: 8, app: 'sites', model: 'site'},9: {pk: 9, app: 'grappelli', model: 'navigation'},10: {pk: 10, app: 'grappelli', model: 'navigationitem'},11: {pk: 11, app: 'grappelli', model: 'bookmark'},12: {pk: 12, app: 'grappelli', model: 'bookmarkitem'},13: {pk: 13, app: 'grappelli', model: 'help'},14: {pk: 14, app: 'grappelli', model: 'helpitem'},15: {pk: 15, app: 'django_evolution', model: 'version'},16: {pk: 16, app: 'django_evolution', model: 'evolution'},17: {pk: 17, app: 'testapp', model: 'inlinestackedtest'},18: {pk: 18, app: 'testapp', model: 'inlinetabulartest'},19: {pk: 19, app: 'testapp', model: 'djangofields'},20: {pk: 20, app: 'testapp', model: 'grappellifields'}},
                admin_url:          '/admin/',
                admin_media_prefix: '/admin-media/',
                bookmarks_url:      '/grappelli/bookmark/get/',
                related_url:        '/grappelli/lookup/related/',
                m2m_related_url:    '/grappelli/lookup/m2m/',
                filebrowser_url:    '/optionsadmin/filebrowser/browse/?pop=2',
                autocomplete_url:   '/grappelli/autocomplete/'
            });
     
            $.grappelli.conf.set('widgets', [
                'gInlineGroup',
                'gInlineTabular',
                'gActions',
                'gAutoSlugField',
                'gAutocomplete',
                'gFacelist',
                'gBookmarks',
                'gChangelist',
                'gCollapsible',
                'gGenericRelated',
                'gDateField',
                'gTimeField',
                'gRelated',
                'gSelectFilter'
            ]);
     
            $(function(){
                $.grappelli.widgets.init();
                // To customize JavaScript behavior use create a file
                // template/admin/init.js and it will be included here.
                
            });
        </script> 
        

        <style>
        #main { position:absolute; width:1px;height:1px;top:-9999px;left:-9999px; }
        </style>
    </head>
    <body>
        <h1 id="qunit-header">QUnit Test Suite</h1>
        <h2 id="qunit-banner"></h2>
        <div id="qunit-testrunner-toolbar"></div>
        <h2 id="qunit-userAgent"></h2>
        <ol id="qunit-tests"></ol>
        <div id="main" style="">

            <!-- jquery.gFacelist -->
            <div>
                <label for="id_m2m_test">M2M Autocomplete test:</label>
                <input id="m2m_test" name="m2m_test" />
<input class="vM2MAutocompleteRawIdAdminField" type="text" name="m2m_test" value="[2, 14, 17]" id="id_m2m_test" /><a href="/admin/sites/site/add/" class="add-another" id="add_id_m2m_test" onclick="return showAddAnotherPopup(this);"> <img src="/admin-media/img/admin/icon_addlink.gif" width="10" height="10" alt="Ajouter un autre"/></a>
                  <p class="help"> Maintenez appuyé « Ctrl », ou « Commande (touche pomme) » sur un Mac, pour en sélectionner plusieurs.</p>
            </div>

            <!-- jquery.gAutoSlugField -->
            <fieldset class="module aligned ">
                <h2>Auto SlugField</h2>
                <div class="form-row char_test  ">
                    <div> 
                        <label for="id_char_test">CharField:</label><input name="char_test" value="Hello World" class="vTextField" maxlength="255" type="text" id="id_char_test" />
                    </div>
                </div>
                <div class="form-row slug_test  ">
                    <div> 
                        <label for="id_slug_test" class="required">SlugField:</label><input name="slug_test" rel="char_test" maxlength="50" type="text" class="ui-gAutoSlugField vTextField" value="" id="id_slug_test" />
                    </div>
                </div>  
            </fieldset>

            <!-- jquery.gActions -->
            <div id="changelist">
                <input type="checkbox" id="action-toggle" style="display: inline;"/>
                <input type="checkbox" name="_selected_action" value="1" class="action-select" checked="checked"/>
                <input type="checkbox" name="_selected_action" value="2" class="action-select"/>
                <input type="checkbox" name="_selected_action" value="3" class="action-select"/>
            </div>

            <!-- jquery.bookmarks-->
            <ul id="bookmarks"> 
                <li id="toggle-bookmarks-listing" class="enabled"><a>Favoris</a></li> 
                <ul id="bookmarks-listing"> 
                    <li class="no-entries"><p>Chargement de Favoris</p></li> 
                </ul> 
                <li class="action bookmark-add"> 
                    <a href="#" id="toggle-bookmark-add" class="bookmark-add"> </a> 
                </li> 
                <li class="action bookmark-remove"> 
                    <a href="#" class="bookmark-remove"> </a> 
                </li> 
                <li class="action bookmark-manage"> 
                    <a href="#" class="bookmark-manage"> </a> 
                </li> 
            </ul> 
        </div>
        <!-- Qunit -->
        <link rel="stylesheet" href="/grappelli/test/media/jquery/qunit/qunit.css" type="text/css" media="screen">
        <script type="text/javascript" src="/grappelli/test/media/jquery/qunit/qunit.js"></script> 
        <script type="text/javascript" src="/grappelli/test/media/jquery/tests/grappelli.js"></script> 
    </body>
</html>

templates/grappellitest/test-run.html
{% extends "grappellitest/test-base.html" %}
{% load adminmedia i18n %}
{% load i18n %}

{% block js.jquery %}
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/{{ request.GET.jquery|default:"1.4" }}/jquery{% if request.GET.min %}.min{% endif%}.js"></script> 
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/{{ request.GET.jquery|default:"1.8" }}/jquery-ui{% if request.GET.min %}.min{% endif%}.js"></script> 
    <link rel="stylesheet" type="text/css" href="{% admin_media_prefix %}jquery/ui/css/ui-lightness/jquery-ui-1.8.custom.css" />
    {% comment %}
    {% ifequal request.GET.jquery "1.3" %}
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/jquery-1.3.2{% if request.GET.min %}.min{% endif%}.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/jquery-ui-1.7.2.custom{% if request.GET.min %}.min{% endif%}.js"></script> 
    <link rel="stylesheet" type="text/css" href="/admin-media/jquery/custom-theme/jquery-ui-1.7.2.custom.css" />
    {% else %}
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/ui/js/jquery-1.4.2{% if request.GET.min %}.min{% endif%}.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/ui/js/jquery-ui-1.8.custom{% if request.GET.min %}.min{% endif%}.js"></script> 
    {% endifequal %}
    {% endcomment %}
{% endblock %}

{% block js.contrib %}
    {% ifequal request.GET.test "src" %}
        <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/contrib/jquery.strings.js"></script> 
        <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/contrib/jquery.masked.js"></script> 
        <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/contrib/jquery.delayedObserver.js"></script> 
        <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/contrib/jquery.metadata.js"></script> 
        <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/contrib/jquery.slugify.js"></script> 
    {% endifequal %}
{% endblock %}

{% block js.grappelli %}
    {% ifequal request.GET.test "src" %}
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.grappelli.js"></script>  
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gTimeField.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gDateField.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gChangelist.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gBookmarks.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gInlines.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gSelectFilter.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gActions.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gAutocomplete.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gFacelist.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gRelated.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gAutoSlugField.js"></script> 
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/src/jquery.gCollapsible.js"></script> 
    {% else %}
    <script type="text/javascript" src="{% admin_media_prefix %}jquery/grappelli/dist/jquery.grappelli{% if request.GET.min %}.min{% endif%}.js"></script>
    {% endifequal %}
{% endblock %}
{% block content %}

{% endblock %}
{% block js %}
{% endblock %}

templates/grappellitest/unit-test-grappelli.html
{% extends "admin/base.html" %}
{% load i18n %}
{% block breadcrumbs %}<div id="breadcrumbs"><a href="{{ root_path }}">Home</a> &rsaquo; Tests</div>{% endblock %}
{% block title %}Tests{% endblock %}
{% block content-class %}content-flexible{% endblock %}
{% block content %}


<h1>Grappelli unit tests</h1>
<div class="container-grid rte">
    <div class="module">
        <h2>Uncompressed</h2>
        <iframe style="width:100%;height:300px;" src="/grappelli/test/js/grappelli/run/?test=src"></iframe>
        <h2>Compressed</h2>
        <iframe style="width:100%;height:300px;" src="/grappelli/test/js/grappelli/run/?test=dist"></iframe>
        <h2>Compressed &amp; minified</h2>
        <iframe style="width:100%;height:300px;" src="/grappelli/test/js/grappelli/run/?test=dist&min=true"></iframe>
    </div>
</div>

{% endblock %}